### ISSUE TITLE
TimeSpeed: Extended key configuration

### ISSUE THREAD

**Issue by alexb5dh** [Pathoschild/StardewCommunityMods#5]
Since there is a request #3 to change key functionality and cantorsdust decided to use x2, /2 for a reason I thought about adding extended hotkey configuration.
Basically, it should look something like this:
```json
"Keys": {
  "TickInterval": {
    "Alt+Z": "-10", // add 10 seconds to tick interval
    "Alt+X": "+10", // subtract 10 seconds from tick interval
    "Ctrl+Z": "/2", // halves tick interval
    "Ctrl+X": "*2" // doubles tick interval
  }
}
```
It will support custom number after operation sign (`+`, `-`, `*`, `/`) and any number of hotkeys for any operation. It can contain not only regular modifiers, but also custom key groups like: `A+B` or `Z+X+C`.

Such implementation should be quite intuitive to use and allow wide range of customizations.
This can go as 2.2-beta after non-beta 2.1 is released.
@Pathoschild, what do you think about the idea?

**Comment by Pathoschild** [comment]
That looks good; it would be useful for users who need more control over the tick length, and we could preconfigure some keys by default. The parser would need to be pretty flexible to handle edge cases (e.g. having spaces like `+ 10` or missing signs like `10`), and show useful errors if parsing fails. I'd suggest considering controller support if you're revisiting input, though.

**Comment by alexb5dh** [comment]
The only problem I see it will require reference to JSON.NET again.
Can you give any links on how controller input can be handled in mods?

**Comment by Pathoschild** [comment]
You could avoid referencing Json.NET by mapping the `TickInterval` field to a `Dictionary<string, int>` (or `Dictionary<string, string>` to show friendlier errors for invalid values) and parsing it after it's deserialised, maybe using the `[OnDeserialized]` attribute like we do in `TimeSpeedConfig`.

I usually add controller support by creating a generic input mapping model like [`InputMapConfig<T>`](https://github.com/Pathoschild/StardewMods/blob/lookup-anything/1.11/LookupAnything/Framework/InputMapConfiguration.cs), then [my config model](https://github.com/Pathoschild/StardewMods/blob/lookup-anything/1.11/LookupAnything/Framework/ModConfig.cs) has an `InputMapConfig<Keys>` and `InputMapConfig<Button>`. I have [an intermediate model](https://github.com/Pathoschild/StardewMods/blob/lookup-anything/1.11/LookupAnything/Framework/RawModConfig.cs) which replaces invalid values with the defaults, but you could simplify if you don't want that. Your implementation would be a bit different since you'll be parsing the keys yourself, but the basic principle would work.

**Comment by Pathoschild** [comment]
You could avoid referencing Json.NET by mapping the `TickInterval` field to a `Dictionary<string, int>` (or `Dictionary<string, string>` to show friendlier errors for invalid values) and parsing it after it's deserialised, maybe using the `[OnDeserialized]` attribute like we do in `TimeSpeedConfig`.

**Comment by Pathoschild** [comment]
I usually add controller support by creating a generic input mapping model like [`InputMapConfig<T>`](https://github.com/Pathoschild/StardewMods/blob/lookup-anything/1.11/LookupAnything/Framework/InputMapConfiguration.cs), then [my config model](https://github.com/Pathoschild/StardewMods/blob/lookup-anything/1.11/LookupAnything/Framework/ModConfig.cs) has an `InputMapConfig<Keys>` and `InputMapConfig<Button>`. I have [an intermediate model](https://github.com/Pathoschild/StardewMods/blob/lookup-anything/1.11/LookupAnything/Framework/RawModConfig.cs) which replaces invalid values with the defaults, but you could simplify if you don't want that. Your implementation would be a bit different since you'll be parsing the keys yourself, but the basic principle would work.

You can receive controller input with SMAPI's `ControlEvents.ControllerButtonPressed` and `ControlEvents.ControllerTriggerPressed` events. I usually create a generic input-handling method like `ReceiveInput<T>(T input, InputMapConfig<T> map)` to handle keyboard/controller input in one place.

**Comment by gralewski** [comment]
Thanks for invitation to comment on this idea. I think it is a great one.
What about using mouse, like wheel for example? With modifiers like shift and control?
And since we would have some nice config options like you propose, what about static values, like for example:
```
"Keys": {
  "TickInterval": {
    "Alt+Z": "-10", // add 10 seconds to tick interval
    "Alt+X": "+10", // subtract 10 seconds from tick interval
    "Ctrl+Z": "/2", // halves tick interval
    "Ctrl+X": "*2", // doubles tick interval
    "Shift+Z": "0.5s", // sets tick interval to 0.5s
    "Shift+X": "600s" // sets tick interval to 600s
  }
}
```

**Comment by Pathoschild** [comment]
Closing this since community mods are discontinued. All TimeSpeed changes have been merged into [the original repository](https://github.com/cantorsdust/StardewMods).
